### ISSUE TITLE
Possible best-practice topics to introduce to tutorial readers

### ISSUE THREAD

**Issue by PatrickLouys** [halfer/php-tutorial-text#1]
First of all, thanks for the effort you put into this. Looks like a really good tutorial for someone new to the language.

The only thing that worries me a little is what follows. Until you have a followup tutorial, it might be useful to link a few resources that point the readers in the right direction. Otherwise I feel it is rather likely that they will pick up bad habits without knowing so from one of the many bad tutorials out there.

A few topics that come to mind:
- [Guard clauses](http://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html)
- [OOP](http://code.tutsplus.com/tutorials/object-oriented-php-for-beginners--net-12762)
- [SOLID](http://en.wikipedia.org/wiki/SOLID_%28object-oriented_design%29)
- [Front controller](http://stackoverflow.com/a/20299496/2834339)
- [OWASP Top 10](https://www.owasp.org/index.php/Top_10_2013-Top_10)

I did not give the tutorial an indepth read, so the suggestions might not be suited towards your target audience. Proceed with caution :)

**Comment by halfer** [comment]
The links here would be valuable for a more advanced audience, but as above, I don't think they fit here. Maybe if I do a follow-up tutorial one day. :smile_cat:
