### ISSUE TITLE
Add link to php.net in introduction

### ISSUE THREAD

**Issue by troelsselch** [halfer/php-tutorial-text#20]
When reading the introduction it would be useful if (part of) the text "usually on the PHP website" was a link to php.net.

I can do a pull request if you wish? (I didn't see a CONTRIBUTE file.)

**Comment by halfer** [comment]
Great, thanks! Yes please, just do a pull request against the `v3` branch.

It's a good idea for me to add some contribution guidelines. I did so [for the code base](https://github.com/halfer/php-tutorial-project) but not here - will see if I can find some time to do so.

**Comment by troelsselch** [comment]
This has been done by @michaellenahan, thanks. (I forgot about this and the email notification got lost in my inbox. My apologies.)
