### ISSUE TITLE
Should saving in edit mode go back to edit mode or not?

### ISSUE THREAD

**Issue by kelmster** [halfer/php-tutorial-text#25]
I know it is an old tutorial but I went through it. when I got done I added a post and save it, then it goes directly in to edit. Don't know if I missed something. I will go through it and see if I can see something I was  just letting you know. Thanks for the Awesome tutorial.

**Comment by halfer** [comment]
You're welcome!

From [the code](https://github.com/halfer/php-tutorial-project/blob/rebase4/edit-post.php#L68) it looks like the operation you describe is expected. If there are no errors, it does the save and redirects back to self. Of course, it being a tutorial, you can change that in your copy if you like, once you are done.
