### ISSUE TITLE
Getting SQLite error "Could not run SQL", "syntax error"

### ISSUE THREAD

**Issue by Intoxyc8me** [halfer/php-tutorial-text#26]
Could not run SQL: Array ( [0] => HY000 [1] => 1 [2] => near "UNSIGNED": syntax error )

**Comment by halfer** [comment]
Hi @Intoxyc8me.

It's good to see this tutorial is still in use. However, I may need more information than that to be able to assist!

* What file/URL produces this error?
* What line number?
* What is the SQL you're running when getting this error? You can edit the code to `echo` it temporarily, for the purpose of debugging.

**Comment by halfer** [comment]
Hi @Intoxyc8me. If you can add more information to this, please do, and feel free to reopen.
