### ISSUE TITLE
403 Forbidden when trying to access downloads

### ISSUE THREAD

**Issue by Natfan** [halfer/php-tutorial-text#29]
When clicking on any 'Download' link, you are presented with a [403 Forbidden](https://ilovephp.jondh.me.uk/checkouts/rebase5/8b137435a04eac77404f/index.php) error. That link is from the first download on the first part of the tutorial, but I tested a few others on various pages and they all give me the same result.

**Comment by halfer** [comment]
Thanks for the report. I redeployed this recently, looks like I missed something!

I'll ping you when I've fixed it.

**Comment by halfer** [comment]
I believe that's now fixed, Natfan - would you try on your end?

I am in the process of moving the tutorial to a continuous deployment system, so I'll add a healthcheck for that.

**Comment by Natfan** [comment]
https://ilovephp.jondh.me.uk/checkouts/rebase5/1d454f2557a93de3ea7a/data/init.sql still gives me a 403 on an incognito tab, @halfer

**Comment by halfer** [comment]
Thanks @Natfan, same here. It's late here so I will try tomorrow morning. I tried a bunch of `.php` files, which worked - I wonder if it has a problem with the `.sql` file type? Will investigate.

**Comment by halfer** [comment]
Hmm, I've just run some `chown` and I think I've fixed it - previously I believed I fixed it with `chmod`. I wonder if my container orchestrator is restarting my containers, and so any fixes I make are being reset back to a dud image. I will get some time in the week to fix this permanently.

Try again? :smiley_cat:

**Comment by halfer** [comment]
Ooh, it's reverted. I've started this container up in bare Docker locally, and it happens there too - fine on start up, reverts some time after... will look into it pronto.

**Comment by halfer** [comment]
I _think_ I have fixed it [with this](https://askubuntu.com/a/950732/246048), will keep an eye on it.

**Comment by Natfan** [comment]
Yeah, seems to be working fine with [this random link I tried](https://ilovephp.jondh.me.uk/checkouts/rebase5/1b1fed8a9ddde933d685/lib/common.php). Thanks for your help, you're a credit to the PHP community :)
